# Generated by Django 3.1.1 on 2020-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
