# Generated by Django 3.1.1 on 2020-09-19 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200919_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 17, 10, 7, 132812)),
        ),
    ]
